### ISSUE TITLE
modification des données personnelles

### ISSUE THREAD

**Issue by gaelleresnierlecomte** [betagouv/sante-psy#115]
Bonjour, je me suis inscrite en tant que psychologue sur le site Santé Psy mais les informations me concernant (email et langue parlée) sont incorrectes ce qui fait que je ne reçois pas de demande de contact :
- cela fait deux semaines que je suis sans réponse de mes emails à contact-santepsyetudiants@beta.gouv.fr
- y a-t-il moyen de faire cette modification en ligne directement sur la plate-forme ?

**Comment by polomarcus** [comment]
@gaelleresnierlecomte merci de nous avoir remonté le problème , je crois qu'on avait tout résolu par email ensemble, j'espère que tout est OK de votre côté désormais
